---
de_pkgs: [amethyst]
gui_pkgs: [visual-studio-code, firefox, obsidian]
docker_pkgs: [colima]
os_pkgs: [gnu-sed, gnu-tar, grep, coreutils, bash, kubectl, helm]

font_dir: "{{ ansible_env['HOME'] }}/Library/Fonts"

sb_url: "https://github.com/aadam-ali/second-brain-cli/releases/download/v0.10.0/sb-v0.10.0-darwin-arm64.tar.gz"

# MacOS Specific Vars
homebrew_casks: [aws-vault, docker]
