---
cli_pkgs: [vim, neovim, htop, tmux, jq, fzf, ripgrep, ranger, shellcheck]
de_pkgs: []
gui_pkgs: []
docker_pkgs: []
os_pkgs: []
python_build_deps: []

repositories: [asdf-vm/asdf]

font_dir: "{{ ansible_env['HOME'] }}/.local/share/fonts"
fonts:
  D2Coding: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/D2Coding.tar.xz
  UbuntuMono: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/UbuntuMono.tar.xz
  VictorMono: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/VictorMono.tar.xz

sb_url: "https://github.com/Aadam-Ali/second-brain-cli/releases/download/0.20/sb-0.2.0-linux-amd64.tar.gz"

# MacOS Specific Vars
homebrew_casks: []

# Linux Specific Vars
pkg_repos_signing_keys: {}
pkg_repos: {}
