# -----------------------------------------------------------------------------
# K9s Gruvbox Dark Skin
# Author: [@indiebrain](https://github.com/indiebrain)
# -----------------------------------------------------------------------------

# Styles...
foreground: &foreground "#d4be98"
background: &background "#282828"
current_line: &current_line "#d4be98"
selection: &selection "#3c3735"
comment: &comment "#7c6f64"
cyan: &cyan "#89b482"
green: &green "#a9b665"
orange: &orange "#e78a4e"
magenta: &magenta "#d3869b"
blue: &blue "#7daea3"
red: &red "#ea6962"
yellow: &yellow "#d8a657"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *red
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  help:
    fgColor: *foreground
    bgColor: *background
    keyColor: *magenta
    numKeyColor: *blue
    sectionColor: *green
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: white
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: white
      bgColor: *comment
      activeColor: *blue
    status:
      newColor: *cyan
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *orange
      counterColor: *blue
      filterColor: *magenta
  views:
    charts:
      bgColor: background
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *background
      cursorBgColor: *cyan
      markColor: *yellow
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *selection
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
