---
- name: Pull Repos
  ansible.builtin.git:
    repo: "https://github.com/{{ item }}"
    dest: "{{ ansible_env['HOME'] }}/Repos/tools/{{ item | split('/') | last }}"
    depth: 1
    clone: yes
    update: yes
  loop: "{{ repositories }}"
