---
- name: Retrieve GPG Keys For Package Repositories
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ item.key }}"
  become: true
  loop: "{{ pkg_repos_signing_keys | dict2items }}"

- name: Add Package Repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.value }}"
    filename: "{{ item.key }}"
    state: present
  become: true
  loop: "{{ pkg_repos | dict2items }}"

- name: Update Apt Cache & Packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true
    update_cache: true
  become: true

- name: Install CLI Packages
  ansible.builtin.apt:
    name: "{{ cli_pkgs }}"
    state: present
  become: true

- name: Install Distro Specific Packages
  ansible.builtin.apt:
    name: "{{ os_pkgs }}"
    state: present
  become: true

- name: Install Python Build Dependencies
  ansible.builtin.apt:
    name: "{{ python_build_deps }}"
    state: present
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_pkgs }}"
    state: present
  become: true

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
  become: true

- name: "Add '{{ ansible_user_id }}' To Docker Group"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true

- name: Add Flathub Flatpak Repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpaks (gui_pkgs)
  community.general.flatpak:
    name: "{{ gui_pkgs }}"
    state: latest

- name: Install Desktop Environment Packages
  ansible.builtin.apt:
    name: "{{ de_pkgs }}"
    state: present
  become: true

- name: Create Desktop Entry For i3 With .xinitrc
  ansible.builtin.copy:
    src: i3-custom.desktop
    dest: /usr/share/xsessions/i3-custom.desktop
    owner: root
    group: root
    mode: '0644'
  become: true
  when: '"i3" in de_pkgs'
