---
- name: Update Homebrew & Packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install Standard Packages
  community.general.homebrew:
    name: "{{ common_pkgs + os_pkgs }}"
    state: present

- name: Install Docker
  community.general.homebrew:
    name: "{{ docker_pkgs }}"
    state: present

- name: Upgrade Homebrew Casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Install Casks
  community.general.homebrew_cask:
    name: "{{ casks }}"
    state: present

- name: Install Virtualisation Packages
  community.general.homebrew_cask:
    name: "{{ virtualisation_pkgs }}"
    state: present
  when: ansible_facts['virtualization_role'] != 'guest'
