---
- name: Update Homebrew & Packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install CLI Packages
  community.general.homebrew:
    name: "{{ cli_pkgs }}"
    state: present

- name: Install OS Specific Packages
  community.general.homebrew:
    name: "{{ os_pkgs }}"
    state: present

- name: Install Python Build Dependencies
  community.general.homebrew:
    name: "{{ python_build_deps }}"
    state: present

- name: Install Docker
  community.general.homebrew:
    name: "{{ docker_pkgs }}"
    state: present

- name: Upgrade Homebrew Casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Install General Casks
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: present

- name: Install GUI Applications
  community.general.homebrew_cask:
    name: "{{ gui_pkgs }}"

- name: Install Desktop Environment Packages
  community.general.homebrew_cask:
    name: "{{ de_pkgs }}"
