---
- name: Include distro specific variables (Debian)
  include_vars: "debian.yml"
  when: ansible_facts['os_family']|lower == 'debian'

- name: Include OS specific variables (MacOS)
  include_vars: "macosx.yml"
  when: ansible_facts['distribution']|lower == 'macosx'
