#!/usr/bin/env bash

repo=$1

repo=${repo#https://github.com/}
repo=${repo#git@github.com:}

repo_name=${repo##*/}
repo_name=${repo_name%'.git'}
user=${repo%%/*}

path="$REPOS/$user/$repo_name"
git clone $1 $path
