#!/usr/bin/env bash
config_dir="${HOME}/.config/coauth"

coauthors="${config_dir}/coauthors"
template="${config_dir}/git-template"

if [[ ! -d "${config_dir}" ]]; then
  mkdir -p "${config_dir}"
  true > "${coauthors}"
  true > "${template}"
fi

[[ ! -f "${coauthors}" ]] && true > "${coauthors}"
[[ ! -f "${template}" ]] && true > "${template}"

help () {
  cat << EOF
 USAGE:

   coauth help
   coauth add [tag]
   coauth list
   coauth restart
   coauth show
   coauth start
   coauth stop
EOF
}

command_not_found () {
  echo "coauth: unexpected command '$1'"
  echo "Try 'coauth help' for more information"
  exit 1
}

add () {
  if [[ "$1" ]]; then
    echo "$1" >> "${coauthors}"
    echo "Added $1 to ${coauthors}"
  else
    echo "Usage: coauth add <tag>"
  fi
}

stop () {
  true > "${template}"
  git config --global --unset commit.template
  printf "\e[31mPairing mode disabled. Run 'coauth start' to start session.\e[0m\n"
}

list () {
  awk NF "${coauthors}"
}

restart () {
  start
}

show () {
  awk NF "${template}"
}

start () {
  git config --global commit.template "${template}"

  echo -e "\n" > "${template}"
  while true; do
    author=$(fzf < "${coauthors}")

    if [[ "${author}" ]]; then
        echo "Co-authored-by: ${author}" >> "${template}"
        echo "Added co-author: ${author}"
    else
        printf "\e[32mPairing mode enabled.\e[0m\n"
        echo "Run 'coauth stop' to end session. Run 'coauth reset' to change co-authors"
        break
    fi
  done
}

case "$1" in
  "" | "help")
    help
    ;;
  "add")
    shift
    add "$@"
    ;;
  "stop")
    stop
    ;;
  "list")
    list
    ;;
  "restart")
    restart
    ;;
  "show")
    show
    ;;
  "start")
    start
    ;;
  *)
    command_not_found "$@"
    ;;
esac
