#!/usr/bin/env bash

set -euo pipefail

selected=$(find "$REPOS" -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | fzf --tmux center || echo "")
name=$(basename "$selected")

if [[ -z "$selected" ]]; then
  exit 0
fi

tmux -2 new-window -S -c "$REPOS/$selected" -n "$name"
