#!/usr/bin/env bash

selected=$(find "$REPOS"/* -mindepth 1 -maxdepth 1 -type d | fzf)
name=$(basename "$selected")

if [[ -z "$selected" ]]; then
  exit 0
fi

tmux -2 new-window -S -c "$selected" -n "$name"
