#!/bin/bash

set -euo pipefail

CHOICE="${1:-}"

ALACRITTY_CONF="$XDG_CONFIG_HOME/alacritty/alacritty.toml"
VIM_CONF="$HOME/.vimrc"
NVIM_CONF="$XDG_CONFIG_HOME/nvim/lua/plugins/colorscheme.lua"

if [[ "$CHOICE" =~ ^(d|da|dar|dark)$ ]]; then
  DESIRED_MODE="dark"
elif [[ "$CHOICE" =~ ^(l|li|lig|ligh|light)$ ]]; then
  DESIRED_MODE="light"
else
  DESIRED_MODE=$(echo -e "dark\nlight" | fzf)
fi

sed_vim_colorscheme() {
  sed -i "s/set bg=\([a-z]*\)/set bg=${1}/g" "$VIM_CONF"
}

sed_nvim_colorscheme() {
  sed -i "s/vim\.opt\.background = \"\([a-z]*\)\"/vim\.opt\.background = \"${1}\"/g" "$NVIM_CONF"
}

sed_alacritty_colorscheme() {
  sed -i "s#\(themes/\).*\(\.toml\)#\1${1}\2#" "$ALACRITTY_CONF"
}

# Modified from https://shapeshed.com/vim-tmux-alacritty-theme-switcher
switch_vim_theme() {
  tmux list-panes -a -F '#{pane_id} #{pane_current_command}' |
    grep vim | # this captures vim and nvim
    cut -d ' ' -f 1 |
    xargs -I PANE tmux send-keys -t PANE ESCAPE \
      ":set background=${1}" ENTER
  echo "Refreshed all Vim & NeoVim sessions"
}

sed_alacritty_colorscheme "$DESIRED_MODE"
sed_vim_colorscheme "$DESIRED_MODE"
sed_nvim_colorscheme "$DESIRED_MODE"
switch_vim_theme "$DESIRED_MODE" || true
