#!/usr/bin/env bash

set -euo pipefail

ANSIBLE_BECOME_EXE="sudo" # https://github.com/ansible/ansible/issues/85837
ANSIBLE_VERSION="13.6.0"
MISE_VERSION="v2026.4.20"

OS=$(uname)
DIST=$(grep '^ID=' /etc/os-release | cut -d'=' -f2 || true)
DIST_VERSION=$(grep '^VERSION_ID=' /etc/os-release | cut -d'=' -f2 | tr -d '"' || true)
DOTFILES="$HOME/Repos/aadam-ali/dotfiles"
DOTFILES_VENV="$DOTFILES/.venv"
CONFIG_DIR="$HOME/.config"

HTTP=0
while getopts "h" opt; do
  case $opt in
    h) HTTP=1 ;;
    \?) echo "Error: Invalid option provided" >&2; exit 1 ;;
  esac
done

function prepare_linux() {
  echo "Installing pre-requisites..."
  if [[ "${DIST}" == "fedora" ]]; then
    sudo dnf update -y
    sudo dnf install git python3-libdnf5 curl wget -y
  else
    sudo apt-get update -y && sudo apt-get upgrade -y
    sudo apt-get install -y git python3-pip python3-venv curl wget
    if [[ "${DIST}" == "ubuntu" && "${DIST_VERSION}" == "26.04" ]]; then
      sudo apt-get install -y software-properties-common
      ANSIBLE_BECOME_EXE="sudo.ws"
    fi

  fi

  if [[ ! -x $(command -v mise) ]]; then
    echo "Installing mise..."
    mkdir -p "$HOME/.local/bin"
    curl -L "https://github.com/jdx/mise/releases/download/$MISE_VERSION/mise-$MISE_VERSION-linux-x64" > "$HOME/.local/bin/mise"
    chmod +x "$HOME/.local/bin/mise"
  else
    echo "Upgrading mise..."
    mise self-update
  fi
}

function prepare_macos() {
  echo "Installing pre-requisites..."
  if [[ ! $(which brew) ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  brew install python@3.14
}

function install_ansible() {
  echo "Installing ansible..."
  if [[ ! -d "$DOTFILES_VENV" ]]; then
    python3 -m venv "$DOTFILES_VENV"
  fi

  if [[ ! -f "$DOTFILES_VENV/bin/ansible" ]]; then
    "$DOTFILES_VENV"/bin/pip install ansible=="$ANSIBLE_VERSION"
  fi
}

function create_ssh_key() {
  if [[ ! -f "$HOME/.ssh/id_ed25519" ]]; then
    mkdir -p "$HOME/.ssh"
    ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519" -N ''

    echo "======================= Add the following key to GitHub ======================="
    cat "$HOME/.ssh/id_ed25519.pub"
    echo "==============================================================================="

    read -r -p "Press enter to continue ..." </dev/tty
  fi
}

function pull_dotfiles_repo() {
  repo_url="git@github.com:aadam-ali/dotfiles"
  if [[ $HTTP == 1 ]]; then
    repo_url="https://github.com/aadam-ali/dotfiles"
  fi


  if [[ ! -d "$DOTFILES" ]]; then
    echo "Cloning $repo_url"
    mkdir -p "$HOME/Repos/aadam-ali"
    git clone "$repo_url" "$DOTFILES"
    cd "$DOTFILES"
  else
    cd "$DOTFILES"
    git stash -q
    git pull
    git stash pop -q || true
  fi
}

function symlink_dotfiles() {
  echo "Creating symlinks to config files..."
  [[ ! -f $HOME/.bash_local ]] && touch "$HOME/.bash_local"

  ln -sf "$PWD/home/.profile" "$HOME/.profile"
  ln -sf "$PWD/home/.bashrc" "$HOME/.bashrc"
  # shellcheck disable=SC1091
  source "$HOME/.bashrc"

  [[ ! -d $HOME/.vim/autoload ]] && mkdir -p "$HOME/.vim/autoload"
  ln -sf "$DOTFILES/home/vim/.vimrc" "$HOME/.vimrc"
  ln -sf "$DOTFILES/home/vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
  ln -nsf "$DOTFILES/config/nvim" "$HOME/.config/nvim"

  ln -nsf "$DOTFILES/config/tmux" "$HOME/.config/tmux"
  ln -nsf "$DOTFILES/config/git" "$HOME/.config/git"

  if [[ ${OS} == "Linux" ]]; then
    ln -nsf "$DOTFILES/config/alacritty" "$HOME/.config/alacritty"
    ln -nsf "$DOTFILES/config/rofi" "$HOME/.config/rofi"
    ln -nsf "$DOTFILES/config/waybar" "$HOME/.config/waybar"
    ln -nsf "$DOTFILES/config/sway" "$HOME/.config/sway"
  fi
}

function run_ansible_playbook() {
  echo "Running ansible playbook..."
  ANSIBLE_BECOME_EXE="${ANSIBLE_BECOME_EXE}" "$DOTFILES_VENV"/bin/ansible-playbook --diff --verbose --ask-become-pass --inventory ansible/hosts ansible/playbook.yml
}

function main() {
  if [[ ${OS} == "Linux" ]]; then
    prepare_linux
  elif [[ ${OS} == "Darwin" ]]; then
    prepare_macos
  fi

  [[ ! -d "$CONFIG_DIR" ]] && mkdir "$CONFIG_DIR"

  create_ssh_key
  pull_dotfiles_repo
  symlink_dotfiles
  install_ansible
  run_ansible_playbook
}

main
