#!/usr/bin/env bash

cd $NOTES

_select_note() {
    # This currently requires > 1 note to be present to work as expected
    grep --max-count=1 '# ' ./*/*.md | # Get list of notes <path>:# <title>
    sed -e 's/README.md//g' -e 's/# / /g' | # Change format to ./<id>/: <title>
    sed -e 's/\.\///g' -e 's/\///1' | fzy  # Select note in format <id>: <title>
}

link_note() {
    # Generate link for note for another
    _select_note |  awk -F ": " '{print "* ["$1"](/"$1"/) "$2}'
}

open_note() {
    # Opens note in EDITOR (needs to be set in .bashrc / .profile)
    $EDITOR $(_select_note | awk -F ": " '{print $1"/README.md"}')
}

display_note() {
    # Outputs note to the terminal
    cat $(_select_note | awk -F ": " '{print $1"/README.md"}')
}

new_note() {
    # Opens a new note in EDITOR with an ID in datetime format YYYYMMDDhhmmss
    datetime=$(date +%Y%m%d%H%M%S)

    mkdir $NOTES/$datetime
    file=$NOTES/$datetime/README.md

    echo "# $@" > $file
    $EDITOR $file
}

case "$1" in
    "" | print | p)
        display_note ;;
    open | o)
        open_note ;;
    new | n)
        shift
        new_note "$@" ;;
    link | l)
        link_note ;;
esac
