---
# Add GPG keys for apt repositories
- name: Retrieving GPG Key For Hashicorp Apt Repository
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc 
  become: true

- name: Retrieving GPG Key For Virtualbox Apt Repository
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: /usr/share/keyrings/oracle_vbox_2016.asc
  become: true

- name: Retrieving GPG Key For VSCode Apt Repository
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc 
    dest: /usr/share/keyrings/microsoft.asc
  become: true

- name: Retrieving GPG Key For Docker Apt Repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker.asc
  become: true

# Add apt repositories to sources.list.d/
- name: Adding Hashicorp Apt Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present
  become: true

- name: Adding Virtualbox Apt Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox_2016.asc] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    filename: virtualbox
    state: present
  become: true

- name: Adding VSCode Apt Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present
  become: true

- name: Adding Docker Apt Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  become: true

# Updating all packages and install any specific packages
- name: Updating Apt Packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true
    update_cache: true
  become: true

- name: Installing Docker With Apt
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
    state: latest
  become: true

- name: Installing Packages With Apt
  ansible.builtin.apt:
    name:
      - code
      - fzy
      - htop
      - python3-venv
      - tmux
      - vagrant
      - vim
      - virtualbox-7.0
    state: latest 
  become: true
