---
- name: Bootstrapping New Machine
  hosts: local
  connection: local

  tasks:
  - name: Add GPG Keys For apt Repositories and Update Packages
    ansible.builtin.import_tasks: 
      file: debian.yml
    when:
      - ansible_facts['os_family'] == 'Debian'

  - name: Run Bootstrapping Commands for MacOS
    ansible.builtin.import_tasks:
      file: mac.yml
    when:
      - ansible_facts['distribution'] == 'MacOSX'

  - name: Setup Docker
    ansible.builtin.import_tasks:
      file: docker.yml
    when:
      - ansible_facts['os_family'] == 'Debian'

