---
- name: Stashing Local Dotfiles Changes
  ansible.builtin.shell:
    cmd: "git stash"
    chdir: "{{ ansible_env['HOME'] }}/Repos/Aadam-Ali/dotfiles"

- name: Pulling Dotfiles
  ansible.builtin.git:
    repo: git@github.com:Aadam-Ali/dotfiles.git
    dest: "{{ ansible_env['HOME'] }}/Repos/Aadam-Ali/dotfiles"
    clone: yes
    update: yes

- name: Unstashing Local Dotfiles Changes
  ansible.builtin.shell:
    cmd: "git stash pop; exit 0;" # exit 0 to avoid Ansible reporting no stash entries as a failure
    chdir: "{{ ansible_env['HOME'] }}/Repos/Aadam-Ali/dotfiles"