---
- name: Pulling pyenv
  ansible.builtin.git:
    repo: "git@github.com:pyenv/pyenv.git"
    dest: "{{ ansible_env['HOME'] }}/Repos/tools/pyenv"
    depth: 1
    clone: yes
    update: yes

- name: Pulling tfenv
  ansible.builtin.git:
    repo: "git@github.com:tfutils/tfenv.git"
    dest: "{{ ansible_env['HOME'] }}/Repos/tools/tfenv"
    depth: 1
    clone: yes
    update: yes

# Vim Plugins

- name: Pulling vim-python
  ansible.builtin.git:
    repo: "git@github.com:vim-python/python-syntax.git"
    dest: "{{ ansible_env['HOME'] }}/.vim/pack/plugins/start/python-syntax"
    depth: 1
    clone: yes
    update: yes

- name: Pulling vim-code-dark
  ansible.builtin.git:
    repo: "git@github.com:tomasiser/vim-code-dark.git"
    dest: "{{ ansible_env['HOME'] }}/.vim/pack/themes/start/codedark"
    depth: 1
    clone: yes
    update: yes
