# -*- conf -*-

shell="/usr/bin/env bash -lc 'tmux -2 new-session -A -s main'"

term=xterm-256color

font=UbuntuMono Nerd Font Mono:size=18
font-size-adjustment=2

initial-color-theme=1

pad=4x4 center

[colors]
background=282828
foreground=d4be98

# Normal/regular colors (color palette 0-7)
regular0=3c3836  # black
regular1=ea6962  # red
regular2=a9b665  # green
regular3=d8a657  # yellow
regular4=7daea3  # blue
regular5=d3869b  # magenta
regular6=89b482  # cyan
regular7=d4be98  # white

# Bright colors (color palette 8-15)
bright0=3c3836   # bright black
bright1=ea6962   # bright red
bright2=a9b665   # bright green
bright3=d8a657   # bright yellow
bright4=7daea3   # bright blue
bright5=d3869b   # bright magenta
bright6=89b482   # bright cyan
bright7=d4be98   # bright white

[colors2]
background=fbf1c7
foreground=654735

# Normal/regular colors (color palette 0-7)
regular0=654735  # black
regular1=c14a4a  # red
regular2=6c782e  # green
regular3=b47109  # yellow
regular4=45707a  # blue
regular5=945e80  # magenta
regular6=4c7a5d  # cyan
regular7=eee0b7  # white

# Bright colors (color palette 8-15)
bright0=654735   # bright black
bright1=c14a4a   # bright red
bright2=6c782e   # bright green
bright3=b47109   # bright yellow
bright4=45707a   # bright blue
bright5=945e80   # bright magenta
bright6=4c7a5d   # bright cyan
bright7=eee0b7   # bright white

[key-bindings]
# color-theme-switch-1=none
# color-theme-switch-2=none
color-theme-toggle=Control+Shift+m
